version: "3.7"

services:
  mongodb:
    image: mongo:4.2.12
    container_name: roykestereo-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27119:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: roykestereo-mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}

    depends_on:
      - mongodb

  # frontend:
  #   build:
  #     context: ./frontend
  #   restart: always
  #   volumes:
  #     - ./frontend/conf.d:/etc/nginx/conf.d
  #   # ports:
  #   #   - 8000:80
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./backend
  #   restart: always
  #   # ports:
  #   #   - 5000:80
  #   #   - 3000:3000
  #   environment:
  #     DB_USER: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: ${DB_HOST}
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mongodb

  # nginx:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./nginx_conf:/etc/nginx/
  #   depends_on:
  #     - backend
  #     - frontend
  #   ports:
  #     - 80:80

volumes:
  mongodata:

