version: "3.7"

services:
  mongodb:
    image: mongo:4.2.12
    container_name: roykestereo-mongodb
    restart: always
    networks: 
      - roykestereo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27119:27017
    volumes: 
      - mongodata:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: roykestereo-mongo-express
    restart: always
    ports:
      - 8085:8081
    networks: 
      - roykestereo-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME} 
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb 
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME} 
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}

    depends_on:
      - mongodb

volumes:
  mongodata:

networks:
  roykestereo-network:
    driver: bridge